[package]
name = "alloc-madvise"
version = "0.1.0"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
edition = "2018"

[lib]
name = "alloc_madvise"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.80"
allocate = { path = "../allocate" }
