name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: Run doctests
      run: cargo test --doc --verbose
    - name: Build docs
      run: cargo doc
